service: sqs-worker
frameworkVersion: '2 || 3'

plugins:
  - serverless-lift
  - serverless-offline
  - serverless-offline-aws-eventbridge

custom:
  serverless-offline-aws-eventbridge:

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: ap-northeast-2
  profile: 'my-admin-profile'

constructs:
  jobs:
    type: queue
    worker:
      handler: src/handler.consumer

functions:
  producer:
    handler: src/handler.producer
    events:
      - httpApi:
          method: post
          path: /produce
    environment:
      QUEUE_URL: ${construct:jobs.queueUrl}
  scheduler:
    handler: src/handler.scheduler
    events:
      - schedule:
          rate: rate(1 minutes)
  consumer:
    handler: src/handler.consumer
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn